version: "3"

services:
    php:
        container_name: ${CONTAINER_NAME}_php
        build: ./conf/php
        restart: always
        ports:
            - ${REMOTE_IP}:${PHP_PORT}:80
        volumes:
            - ./conf/apache2/sites-available:/etc/apache2/sites-available
            - ./data/www:/var/www/html:cached
        links:
            - mysql:mysql
        environment:
            - MARIADB_HOST=mysql
            - MARIADB_PORT_NUMBER=3306
            - PRESTASHOP_HOST=localhost:${PHP_PORT}
            - PRESTASHOP_DATABASE_USER=${MYSQL_USER}
            - PRESTASHOP_DATABASE_PASSWORD=${MYSQL_PASSWORD}
            - PRESTASHOP_DATABASE_NAME=${MYSQL_DATABASE}
            # /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            #- PHP_EXTENSION_XDEBUG=${X-DEBUG}
            #- PHP_IDE_CONFIG="serverName=${CONTAINER_NAME}_php"
            #- XDEBUG_CONFIG=remote_host=host.docker.internal remote_port=9000 remote_enable=1

    mysql:
        container_name: ${CONTAINER_NAME}_mysql
        image: mariadb:latest
        restart: always
        #ports:
        #    - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            - MARIADB_USER=${MYSQL_USER}
            - MARIADB_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

networks:
    default:
       external:
         name: ${NETWORK}
