version: "3"

services:

  mysql:
    build: ./bin/mysql
    container_name: "${CONTAINER_NAME}_mysql"
    restart: 'always'
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - MARIADB_USER=root
      - MARIADB_DATABASE=prestashop
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${CONTAINER_NAME}_phpmyadmin"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - ${REMOTE_IP}:${PHPMYADMIN_PORT}:80
    volumes:
      - ./data/phpmyadmin/session:/sessions
      - ./data/var/run:/var/run

networks:
    default:
       external:
         name: ${NETWORK}
